import Head from "next/head";
import { useSockets } from "../../context/socketContext";
import { useEffect, useState } from "react";

export default function Home() {
  const { socket } = useSockets();
  return (
    <>
      <Head>
        <title>Connect App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Connect app pracrice</h1>
        {socket.id}
      </main>
    </>
  );
}
